version: '3'
services:
  worker: &base
    image: rabbit-base-image
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    volumes:
      - ./:/app
    # env_file: .env
    ports:
      - 9229:9229
    depends_on:
      - rabbitmq
